apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jfechava
    provider: github
    repository: spring-boot-http-gradle
  name: jfechava-spring-boot-http-gradle
spec:
  description: Imported application for jfechava/spring-boot-http-gradle
  httpCloneURL: https://github.com/jfechava/spring-boot-http-gradle.git
  org: jfechava
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: spring-boot-http-gradle
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jfechava/spring-boot-http-gradle.git
